name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  doc:
    name: Document
    runs-on: ubuntu-latest
    env:
      DISABLE_AWS_CLIENT_CHECK: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Generate document
      run: bundle exec bin/toolbox docgen > doc/resource_types.md

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        add: 'doc/resource_types.md'
  test:
    name: Test
    needs: [ doc ]
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.1'
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
    runs-on: ubuntu-latest
    env:
      DISABLE_AWS_CLIENT_CHECK: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install xml lib
      run: gem install ox
      if: matrix.ruby-version == '3.0'

    - name: Run tests
      run: bundle exec rake spec
